name: Production Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types: [opened, reopened]

jobs:
 test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests..."

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to Production"
